dist: trusty
sudo: required

language: node_js

node_js:
  - "4"

env:
  global:
  # GITHUB_TOKEN
  - secure: "vaLN8sBXqmMxzXIJjgDhnauNdJ5Olo2cgCEySHf5nRp2St0ZwBhSl/OWNq9OXIPGEEAMsLBNk+kBggMxd3reFBLPHbHvyhhrl/odacWlH4P38KccQv2V/qqP7rpxoSfFbT6f7QgiuWt4bD0hZcWSEE/UaiHgcA3jjLD6Gtm0rkMTaKll0pICTe5Nn52sI4+G/SgCkktsi5tXMZLZu7fT9l3vvImEvcqawkEMYKbTjvTrriClAb0aKXMGVm9EOOmSUSYB0gUvV/Ga3/0zt9YbGBYeGLaWIqCDsrvWqk323SGLghcpZgSpF9sQKcKUkgfzRBFfWdFLEXcFofjk7FQpfixuAV5DIrBPPGlFGM8H1qq5A3FnxUhg0R2eaTq+J1a++oe0n0cPNvgGj2p/TLXOat0IfGLN9cNJE8u1GJhXSthRI+8tytp2MhVJ94QUygP11GNkvvj8V8AyuI6SZbeXerwakxS01nvJy/FqrqngXPxLw+5vrGXBV9S/3WcmHuIaiYcgRSs6wlfXjyJy0z08r2w/ygDzNtPDDMFL4bukW6D0REdLdczLxON2DacPUDACQYHImublzJRckSl55Ck+16cRRnZPDXKwYIv5a6LKq2f0QpUeugYlvC65yJsnkKcXPPQV7Pc16Rj04Jb56EZ4eohuPi8jG4xsL0tji7LNOVo="
  - PALETTE_VERSION=2.1.$TRAVIS_BUILD_NUMBER CONTROLLER_VERSION=2.1.$TRAVIS_BUILD_NUMBER
  - OWNER=palette-software
  - PACKAGE=palette

before_install:
  - sudo apt-get install -y debhelper
  - sudo apt-get install -y pylint
  - sudo apt-get install -y python-dateutil # make controller
  - sudo apt-get install -y python-mako python-passlib # make palette
  - sudo dpkg --install --force-depends dependencies/akiri.framework_0.5.6_all.deb # ignore dependencies
  - sudo apt-get install -f # fixing akiri framework dependencies
  - sudo apt-get install -y reprepro # deb sign
  - npm install grunt -g

install:
  - pushd app
  - make setup
  - popd

script:
  - make palette
  - make controller
    # - make clean all
  - cp dependencies/*.deb dpkg/pool/
  - GNUPGHOME=dpkg/keys reprepro -b dpkg/apt includedeb stable dpkg/pool/*.deb

after_success:
  # Create the zip package for GitHub release
  - export PCKG_FILE=palette-${PALETTE_VERSION}.zip
  - zip -r $PCKG_FILE dpkg/apt

# before_deploy:
#   # This line fixes PATH warnings for some reason
#   - rvm use ruby-2.2.3
#   # Install SpiderMonkey (renamed to libmozjs) as it is a dependency for jsawk
#   - sudo add-apt-repository ppa:launchpad/ppa -y
#   - sudo apt-get update
#   - sudo apt-get install libmozjs-24-bin
#   - ls -lah /usr/bin/js24
#   - which js24
#   - which js
#   - sudo update-alternatives --install /usr/bin/js js /usr/bin/js24 10
#   - which js
#   - echo "PATH:"
#   - echo $PATH
#   # Make sure jsawk is installed, it is a dependency for release-to-github.sh
#   - curl -L http://github.com/micha/jsawk/raw/master/jsawk > jsawk
#   - chmod 755 jsawk
#   - sudo mv jsawk /usr/local/bin
#   - which jsawk
#   - jsawk -h
#   - >
#     jsawk -s "{\"id\": \"asd\"}" -a "return this.id"
#   # - sudo ln -s jsawk /usr/bin/jsawk
#   # - sudo chown $USER:$USER /usr/bin/jsawk

deploy:
  skip_cleanup: true
  provider: script
  # Only deploy from the master branch (and if we don't have a tag specified, because they are auto-committed)
  script: $TRAVIS_BUILD_DIR/release-to-github.sh
  on:
    branch: master
    tags: false

notifications:
  email: false
