sudo: required

# do not build tag
branches:
  except:
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

language: bash

env:
  global:
  # GITHUB_TOKEN
  - secure: "vaLN8sBXqmMxzXIJjgDhnauNdJ5Olo2cgCEySHf5nRp2St0ZwBhSl/OWNq9OXIPGEEAMsLBNk+kBggMxd3reFBLPHbHvyhhrl/odacWlH4P38KccQv2V/qqP7rpxoSfFbT6f7QgiuWt4bD0hZcWSEE/UaiHgcA3jjLD6Gtm0rkMTaKll0pICTe5Nn52sI4+G/SgCkktsi5tXMZLZu7fT9l3vvImEvcqawkEMYKbTjvTrriClAb0aKXMGVm9EOOmSUSYB0gUvV/Ga3/0zt9YbGBYeGLaWIqCDsrvWqk323SGLghcpZgSpF9sQKcKUkgfzRBFfWdFLEXcFofjk7FQpfixuAV5DIrBPPGlFGM8H1qq5A3FnxUhg0R2eaTq+J1a++oe0n0cPNvgGj2p/TLXOat0IfGLN9cNJE8u1GJhXSthRI+8tytp2MhVJ94QUygP11GNkvvj8V8AyuI6SZbeXerwakxS01nvJy/FqrqngXPxLw+5vrGXBV9S/3WcmHuIaiYcgRSs6wlfXjyJy0z08r2w/ygDzNtPDDMFL4bukW6D0REdLdczLxON2DacPUDACQYHImublzJRckSl55Ck+16cRRnZPDXKwYIv5a6LKq2f0QpUeugYlvC65yJsnkKcXPPQV7Pc16Rj04Jb56EZ4eohuPi8jG4xsL0tji7LNOVo="
  - PALETTE_VERSION=3.0.$TRAVIS_BUILD_NUMBER CONTROLLER_VERSION=3.0.$TRAVIS_BUILD_NUMBER
  - OWNER=palette-software
  - PACKAGE=palette
  - DEPLOY_HOST=palette-rpm.brilliant-data.net
  - DEPLOY_PATH=/var/palette-rpm-repo
  - DEPLOY_USER=palette-rpm
  # DEPLOY_PASS
  - secure: i+eeiUMC7fC8IC+Qz3gADeWWEL1LexL5oUK4b+HcXSyIY5hO+HLyJ/ejnUdpIIX4OL9y5bDDA48lXopZV13gn3MXYd4OW2RDAsf3yADtP77Uq7vE70F7JtrqvgBb6EIcix0Nzdf7bZz08Kgmf2/vJ/zdbcq4QyThbiX1ITDwOP7PAwX3HjXjqG/BRBGdkXD/kby0b/qj1hhQ5U90jAsStDcilW18DvhL9tI5MPvnX32yTtR6llYhSAQfsOZLpv8Ui+RvFNFLxEG4ktktcrkNrS+UfmYNUamb+/k0cWr6FDroJmqoZrfQ2Dp7/mVvXDNU8yIqgUgkXmTGXD4NH1qcFG2S5MMQUKpG70uog8oZFkho0O3EAtXyterJtUd25k6eHoYlTNV6RnwoRXSF5zrJbfQpRrnDFnU9U2Kih7gjt+f/6XQg80E6v8U4u9LmVHGdHLLdMsI9nwGGQ2NN5WR9xy3Rqr77zoNiMnjgMQqqyQCpctQ5v1GqBQwFm8kYMyVoBJ2CkIkeeIrMwqhr+b5LO00Z2t06Fk6iYpT9jnMInZ4BNU67KMnFaH7iI4THCk93uoiHkMf4celFF+oqS2oA2oLX+DGt4YIbLQzZT4OsVhMZX2in3inTBY6NdA/G9M1x2UTQ2NhWZsCYCxixP7jtOIw6lXHwm6+E6Um+PaiHKKw=

# create RPM package with docker
services:
  - docker

addons:
  apt:
    packages:
      # To deploy the rpms, we need to ssh into places, and we dont want to store keys for now
      - sshpass

script:
  - docker/package.rpm/build_and_start_container.sh

after_success:
  # Create the zip package for GitHub release
  - export PCKG_DIR=palette-${PALETTE_VERSION}
  - export PCKG_FILE=palette-${PALETTE_VERSION}.zip
  - zip -r ${PCKG_FILE} ${PCKG_DIR}

before_deploy:
  # Deploy RPMs with noarch dir
  - export DEPLOY_FILE="${TRAVIS_BUILD_DIR}/${PCKG_DIR}/*"

deploy:
  skip_cleanup: true
  provider: script
  # Only deploy from the master branch (and if we don't have a tag specified, because they are auto-committed)
  script: "./deploy.sh"
  on:
    branch: master
    tags: false

notifications:
  email: false
