#!/usr/bin/env python
import sys

from commhandler import CommHandler

if __name__ == "__main__":
    comm = CommHandler()
    if not comm.send_cmd("ziplogs", sync=True, close=False, verbose=True,
                                                    skip_on_wrong_state=True):
        print "ziplogs failed with:", comm.error
    print "ziplogs reply:", comm.data

    if not comm.send_cmd("backup", sync=True, close=False, verbose=True,
                                                    skip_on_wrong_state=True):
        print "backup failed with:", comm.error
    print "backup reply:", comm.data
    sys.exit(0)
    if not comm.send_cmd("cleanup", sync=True, close=True, verbose=True,
                                                    skip_on_wrong_state=True):
        print "cleanup failed with:", comm.error
    print "cleanup data:", comm.data

    sys.exit(0)
