#!/usr/bin/env python
import os
import sys
import time

from controller.palapi import CommHandlerCmd

if __name__ == "__main__":
    # If we ran in the foreground, then it would block sched from
    # running other cron jobs. This can take a long time (too long)
    # which could block backups, etc.
    pid = os.fork()
    if pid:
        sys.exit(0)

    comm = CommHandlerCmd()
    comm.send_cmd("datasource import", skip_on_wrong_state=True,
                   read_response=True)
    comm.send_cmd("datasource fixup", skip_on_wrong_state=True,
                   read_response=False)
    sys.exit(0)
