#!/usr/bin/env python
import sys
import os

from controller.palapi import CommHandlerCmd

if __name__ == "__main__":
    pid = os.fork()
    if pid:
        sys.exit(0)

    os.close(0)
    os.close(1)
    os.close(2)

    comm = CommHandlerCmd()
    comm.send_cmd("extract import", skip_on_wrong_state=True,
                  read_response=True)
    comm.send_cmd("extract archive", skip_on_wrong_state=True,
                  read_response=False)
    sys.exit(0)
