#!/usr/bin/env python
import sys

from controller.palapi import CommHandlerCmd

if __name__ == "__main__":
    comm = CommHandlerCmd()
    comm.send_cmd("extract archive", skip_on_wrong_state=True,
                  read_response=False)
    sys.exit(0)
