#!/usr/bin/env python
import sys

from commhandler import CommHandler

if __name__ == "__main__":
    comm = CommHandler()
    comm.send_cmd("workbook import", skip_on_wrong_state=True)
    sys.exit(0)
