#!/usr/bin/env python
import sys

from controller.palapi import CommHandlerCmd

if __name__ == "__main__":
    comm = CommHandlerCmd()
    comm.send_cmd("sync", skip_on_wrong_state=True, read_response=True)
    sys.exit(0)
