#!/bin/bash
#
# framework-timezone

### BEGIN INIT INFO
# Provides: framework-timezone
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Framework timezone Configurator
# Description: Framework timezone Configuration
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

prog="framework-timezone"
PYTHON_PACKAGE_DIR=$(python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()")
exec=${PYTHON_PACKAGE_DIR}/akiri/framework/servers/utils/timezone.wsgi
pidfile=/var/run/${prog}.pid
RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}

start() {
    echo -n $"Starting $prog: "
    daemon --pidfile=${pidfile} "$exec $OPTIONS >&/dev/null &"
    RETVAL=$?
    echo
    return $RETVAL
}

stop() {
    status -p ${pidfile} $exec > /dev/null
    if [[ $? = 0 ]]; then
        echo -n $"Stopping $prog: "
        killproc -p ${pidfile} -d ${STOP_TIMEOUT} $exec
    else
        echo -n $"Stopping $prog: "
        success
    fi
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${pidfile}
    return $RETVAL
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status -p ${pidfile} $exec
    RETVAL=$?
    ;;
  restart)
    stop
    start
    ;;
  condrestart|try-restart)
    if status -p ${pidfile} $exec >&/dev/null; then
        stop
        start
    fi
    ;;
  force-reload|reload)
    start
    stop
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|condrestart|try-restart|force-reload|reload|status}"
    RETVAL=2
esac

exit $RETVAL
