#!/bin/sh

case "$1" in
    remove|deconfigure)
        # Put it back the way it was.
        sed --in-place 's/#Listen 80/Listen 80/' /etc/apache2/ports.conf
        /usr/sbin/a2dissite palette-software.conf palette-software-ssl.conf
        service apache2 stop || true
        rm -rf /opt/palette/plugins
    ;;
    upgrade)
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
