#!/usr/bin/env python

import sys

# requires: python-requests
import requests

if len(sys.argv) != 2:
    print >> sys.stderr, 'usage: pkg-update <package-name|ALL>'
    sys.exit(1)

value = sys.argv[1]
if value.upper() == 'ALL':
    url = "http://localhost:8080/update"
else:
    url = "http://localhost:8080/update/" + value

data = {'action': 'install'}
req = requests.post(url, data=data)
print(req.text)
if req.status_code == 200:
    sys.exit(0)
else:
    sys.exit(1)
