AGENT_TYPE_PRIMARY="primary"
AGENT_TYPE_WORKER="worker"
AGENT_TYPE_OTHER="other"

MAIN_LOGGER_NAME="main"
STATUS_LOGGER_NAME="status"

DEFAULT_STATUS_SLEEP_INTERVAL=5

# How long to wait between getting cli status
CLI_GET_STATUS_INTERVAL=1
